# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(842, 582)
        self.action_video_devices = QAction(MainWindow)
        self.action_video_devices.setObjectName(u"action_video_devices")
        self.action_video_device_connect = QAction(MainWindow)
        self.action_video_device_connect.setObjectName(u"action_video_device_connect")
        self.action_video_device_disconnect = QAction(MainWindow)
        self.action_video_device_disconnect.setObjectName(u"action_video_device_disconnect")
        self.actionexit = QAction(MainWindow)
        self.actionexit.setObjectName(u"actionexit")
        self.actionResetKeyboard = QAction(MainWindow)
        self.actionResetKeyboard.setObjectName(u"actionResetKeyboard")
        self.actionResetMouse = QAction(MainWindow)
        self.actionResetMouse.setObjectName(u"actionResetMouse")
        self.actionMinimize = QAction(MainWindow)
        self.actionMinimize.setObjectName(u"actionMinimize")
        self.actionReload_Key_Mouse = QAction(MainWindow)
        self.actionReload_Key_Mouse.setObjectName(u"actionReload_Key_Mouse")
        self.actionRelease_mouse = QAction(MainWindow)
        self.actionRelease_mouse.setObjectName(u"actionRelease_mouse")
        self.actionCapture_mouse = QAction(MainWindow)
        self.actionCapture_mouse.setObjectName(u"actionCapture_mouse")
        self.actionReload_MCU = QAction(MainWindow)
        self.actionReload_MCU.setObjectName(u"actionReload_MCU")
        self.action_fullscreen = QAction(MainWindow)
        self.action_fullscreen.setObjectName(u"action_fullscreen")
        self.action_fullscreen.setCheckable(True)
        self.action_Resize_window = QAction(MainWindow)
        self.action_Resize_window.setObjectName(u"action_Resize_window")
        self.actionKeep_ratio = QAction(MainWindow)
        self.actionKeep_ratio.setObjectName(u"actionKeep_ratio")
        self.actionKeep_ratio.setCheckable(True)
        self.actionKeep_on_top = QAction(MainWindow)
        self.actionKeep_on_top.setObjectName(u"actionKeep_on_top")
        self.actionKeep_on_top.setCheckable(True)
        self.actionHide_cursor = QAction(MainWindow)
        self.actionHide_cursor.setObjectName(u"actionHide_cursor")
        self.actionHide_cursor.setCheckable(True)
        self.actionSystem_hook = QAction(MainWindow)
        self.actionSystem_hook.setObjectName(u"actionSystem_hook")
        self.actionSystem_hook.setCheckable(True)
        self.actionRelative_mouse = QAction(MainWindow)
        self.actionRelative_mouse.setObjectName(u"actionRelative_mouse")
        self.actionRelative_mouse.setCheckable(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 842, 26))
        self.menu_video_menu = QMenu(self.menubar)
        self.menu_video_menu.setObjectName(u"menu_video_menu")
        self.menuKeyboard = QMenu(self.menubar)
        self.menuKeyboard.setObjectName(u"menuKeyboard")
        self.menuMouse = QMenu(self.menubar)
        self.menuMouse.setObjectName(u"menuMouse")
        self.menuVideo = QMenu(self.menubar)
        self.menuVideo.setObjectName(u"menuVideo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setSizeGripEnabled(False)
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu_video_menu.menuAction())
        self.menubar.addAction(self.menuVideo.menuAction())
        self.menubar.addAction(self.menuKeyboard.menuAction())
        self.menubar.addAction(self.menuMouse.menuAction())
        self.menu_video_menu.addAction(self.action_video_devices)
        self.menu_video_menu.addAction(self.action_video_device_connect)
        self.menu_video_menu.addAction(self.action_video_device_disconnect)
        self.menu_video_menu.addSeparator()
        self.menu_video_menu.addAction(self.actionReload_MCU)
        self.menu_video_menu.addAction(self.actionReload_Key_Mouse)
        self.menu_video_menu.addSeparator()
        self.menu_video_menu.addAction(self.actionMinimize)
        self.menu_video_menu.addAction(self.actionexit)
        self.menuKeyboard.addAction(self.actionResetKeyboard)
        self.menuKeyboard.addSeparator()
        self.menuKeyboard.addAction(self.actionSystem_hook)
        self.menuMouse.addAction(self.actionResetMouse)
        self.menuMouse.addSeparator()
        self.menuMouse.addAction(self.actionCapture_mouse)
        self.menuMouse.addAction(self.actionRelease_mouse)
        self.menuMouse.addSeparator()
        self.menuMouse.addAction(self.actionRelative_mouse)
        self.menuMouse.addAction(self.actionHide_cursor)
        self.menuVideo.addAction(self.action_fullscreen)
        self.menuVideo.addAction(self.action_Resize_window)
        self.menuVideo.addAction(self.actionKeep_on_top)
        self.menuVideo.addSeparator()
        self.menuVideo.addAction(self.actionKeep_ratio)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"USB KVM Client", None))
        self.action_video_devices.setText(QCoreApplication.translate("MainWindow", u"Video devices", None))
#if QT_CONFIG(shortcut)
        self.action_video_devices.setShortcut("")
#endif // QT_CONFIG(shortcut)
        self.action_video_device_connect.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.action_video_device_disconnect.setText(QCoreApplication.translate("MainWindow", u"Disconnect", None))
        self.actionexit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionResetKeyboard.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.actionResetMouse.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.actionMinimize.setText(QCoreApplication.translate("MainWindow", u"Minimize", None))
        self.actionReload_Key_Mouse.setText(QCoreApplication.translate("MainWindow", u"Reload Key/Mouse", None))
        self.actionRelease_mouse.setText(QCoreApplication.translate("MainWindow", u"Release mouse", None))
        self.actionCapture_mouse.setText(QCoreApplication.translate("MainWindow", u"Capture mouse", None))
        self.actionReload_MCU.setText(QCoreApplication.translate("MainWindow", u"Reload MCU", None))
        self.action_fullscreen.setText(QCoreApplication.translate("MainWindow", u"Fullscreen", None))
        self.action_Resize_window.setText(QCoreApplication.translate("MainWindow", u"Resize window", None))
        self.actionKeep_ratio.setText(QCoreApplication.translate("MainWindow", u"Keep aspect ratio", None))
        self.actionKeep_on_top.setText(QCoreApplication.translate("MainWindow", u"Always on top", None))
        self.actionHide_cursor.setText(QCoreApplication.translate("MainWindow", u"Hide cursor", None))
        self.actionSystem_hook.setText(QCoreApplication.translate("MainWindow", u"System hook", None))
#if QT_CONFIG(statustip)
        self.actionSystem_hook.setStatusTip(QCoreApplication.translate("MainWindow", u"Blocks the system from responding to user input", None))
#endif // QT_CONFIG(statustip)
        self.actionRelative_mouse.setText(QCoreApplication.translate("MainWindow", u"Relative mouse", None))
        self.menu_video_menu.setTitle(QCoreApplication.translate("MainWindow", u"Device", None))
        self.menuKeyboard.setTitle(QCoreApplication.translate("MainWindow", u"Keyboard", None))
        self.menuMouse.setTitle(QCoreApplication.translate("MainWindow", u"Mouse", None))
        self.menuVideo.setTitle(QCoreApplication.translate("MainWindow", u"Video", None))
    # retranslateUi

