name: Build Windows

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: Client/requirements.txt

      - name: Install Dependencies
        run: pip install -r Client/requirements.txt

      - uses: Nuitka/Nuitka-Action@v1.3
        with:
          working-directory: ./Client
          script-name: ./Mini-KVM.py
          mode: app
          enable-plugins: pyside6
          windows-console-mode: disable
          windows-icon-from-ico: ./icons/icon.ico
          include-data-dir: |
            ./icons=icons
            ./Data=data
          include-data-files: |
            ./trans_cn.qm=trans_cn.qm
            ./qtbase_cn.qm=qtbase_cn.qm
          include-qt-plugins: multimedia

      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: Client/build/*.exe
